NUM_OF_BUSHES = 20
BUSH_IMG = "grass.png"
BUSH_HEIGHT = 2
BUSH_WIDTH = 2

WELCOME_MSG = "wcg"

GAME_GRID_ROW = 25
GAME_GRID_COL = 50

SOLDIER_HEIGHT = 4
SOLDIER_WIDTH = 2
SOLDIER_START_LOCATION = [0, 0]
SOLDIER_IMG = "soldier.png"
SOLDIER_BOTTOM_X = 0
SOLDIER_BOTTOM_Y = 50

WINDOW_HEIGHT = 500
WINDOW_WIDTH = 1000
# each square is 20 pixels

BACKGROUND_COLOR = (34, 139, 34)
BACKGROUND_NIGHTCOLOR = (0, 0, 0)

FLAG_WIDTH = 4
FLAG_HEIGHT = 3
FLAG_IMG = "flag.png"

NUM_OF_MINES = 20
MINE_WIDTH = 3
MINE_HEIGHT = 1
MINE_IMG = "mine.png"

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

MINE = 1
FLAG = 2
SOLIDER = 3
EMPTY = 0
